import Head from "next/head";
import styles from "../styles/Home.module.css";
import Products from "../components/Products";
import {
  getCityCoords,
  getHighestUviValue,
  getWeatherData,
  unixDateConverter,
} from "../utils/getWeather";
import { getProductData } from "../utils/getDmData";

export default function Home(props) {
  const { currentDate, currentTemp, products } = props;
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Sonnencremefinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img className={styles.logo} src="/DmBrandClaimIcon.svg" />
        <div className={styles.overview}>
          <h1 className={styles.title}>
            Willkommen zum{" "}
            <a href="https://www.dm.de/search?query=Sonnencreme&searchType=product">
              dm
            </a>{" "}
            Sonnencremefinder! ☀️
          </h1>
          <h1 className={styles.subtitle}>Heute ist der {currentDate}</h1>
          <h3>Aktuell sind es {Math.round(currentTemp)} °C</h3>
        </div>
        <Products products={products} />
        <br />
        <p>
          Die Auswahl des Lichtschutzfaktors wurde anhand des maximalen UV-Index
          der nächsten 5 Tage getätigt
        </p>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤️ and Next.js</p>
        <p>This is a noncommercial website</p>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const city = "Karlsruhe,ger";

  const coords = await getCityCoords(city);
  const weatherData = await getWeatherData(coords.lat, coords.lon);

  const highestUvi = await getHighestUviValue(weatherData);
  const productData = await getProductData(highestUvi);

  const products = productData.products;
  const currentDate = unixDateConverter(weatherData.current.dt);
  const currentTemp = weatherData.current.temp;

  return { props: { products, currentDate, currentTemp } };
}
